### ISSUE TITLE
What is the Spectrogram returning

### ISSUE THREAD

**Issue by aryamansriram** [kongkip/spela#1]
Is the Spectrogram function returning a mel spectrogram or does it need to be explicitly converted?

**Comment by kongkip** [comment]
it returns Spectrogram alone. There is a class called MelSpectrogram, which returns a mel spectrogram. I think that's what you need.

**Comment by aryamansriram** [comment]
Got it thanks alot

**Comment by aryamansriram** [comment]
Sorry for creating the issue, I read the docs clearly now
