### ISSUE TITLE
Melspectrogram vs Librosa

### ISSUE THREAD

**Issue by tauceti12** [kongkip/spela#2]
Hi,

Should the melspectrogram layer return similiar results as librosa? As Kapre claims it has been tested against librosa.

 I've tried to set every parameter similar to librosa's default, but the values I get are differ.

Thanks!

**Comment by kongkip** [comment]
Hi exosome12,
I haven't compared spela's melspectrogram with that of librosa's yet. I
will look into it and get back to you.

Regards,
Evans

**Comment by kongkip** [comment]
Could you please provide an example of how you are doing the comparison.

**Comment by tauceti12** [comment]
yes, tried to simplify my colab notebook, i think this state is the closest i could get. 

[https://colab.research.google.com/drive/1JrMEQ6e_0SKliCtp4jQ9geQz4E4k9gDb?usp=sharing](url)

**Comment by tauceti12** [comment]
I managed to solve my problem using Kapre, did not realize they already have TFlite compatible layers. 
Thanks anyway!
